import jsPDF from "jspdf";



export function exportAnalyticsPDF(
    analytics,
    topFlags
){


    if(!analytics) return;



    const doc = new jsPDF();




    const pageWidth =
    doc.internal.pageSize.width;



    // =========================
    // HEADER
    // =========================


    doc.setFontSize(22);

    doc.text(

        "FeatureFlow",

        20,

        20

    );


    doc.setFontSize(16);

    doc.text(

        "Analytics Report",

        20,

        30

    );



    doc.setFontSize(10);

    doc.text(

        `Generated: ${new Date().toLocaleDateString()}`,

        20,

        40

    );



    doc.line(

        20,

        45,

        pageWidth-20,

        45

    );







    // =========================
    // SUMMARY
    // =========================


    const flags =

    analytics.flags || [];



    const activeFlags =

    flags.filter(

        flag=>flag.enabled

    ).length;



    const totalEvaluations =

    analytics.evaluations?.reduce(

        (sum,item)=>

        sum + item.count,

        0

    ) || 0;





    doc.setFontSize(15);


    doc.text(

        "Summary",

        20,

        60

    );



    doc.setFontSize(11);



    const summary = [

        [

            "Total Flags",

            flags.length

        ],

        [

            "Active Flags",

            activeFlags

        ],

        [

            "Total Evaluations",

            totalEvaluations

        ]

    ];



    let y = 75;



    summary.forEach(item=>{


        doc.roundedRect(

            20,

            y-8,

            170,

            15,

            3,

            3

        );



        doc.text(

            `${item[0]} : ${item[1]}`,

            28,

            y+2

        );



        y += 22;


    });








    // =========================
    // EVALUATION TREND
    // =========================


    y += 10;



    doc.setFontSize(15);


    doc.text(

        "Evaluation Trend",

        20,

        y

    );



    y += 12;



    doc.setFontSize(11);



    analytics.evaluations?.forEach(item=>{


        doc.text(

            `${item.date}     ${item.count}`,

            25,

            y

        );


        y += 8;


    });








    // =========================
    // TOP FLAGS
    // =========================


    y += 10;



    doc.setFontSize(15);


    doc.text(

        "Top Evaluated Flags",

        20,

        y

    );



    y += 12;



    doc.setFontSize(11);



    topFlags?.forEach((flag,index)=>{


        doc.text(

            `${index+1}. ${flag.flag_key} - ${flag.evaluations}`,

            25,

            y

        );


        y += 8;


    });








    // =========================
    // FOOTER
    // =========================


    const pageHeight =

    doc.internal.pageSize.height;



    doc.setFontSize(9);



    doc.text(

        "Generated by FeatureFlow Analytics",

        20,

        pageHeight-10

    );




    doc.save(

        "featureflow-analytics-report.pdf"

    );

}